# Site settings
title: Brasserie El Bocadillo
email: brasserieelbocadillo@gmail.com
phone: 0660258441
description: > # this means to ignore newlines until "baseurl:"
baseurl: '/'
url: 'https://brasserieelbocadillo.fr'

instagram_username: el_bocadillo_beziers

# Build settings
markdown: kramdown
