# Site settings
title: Brasserie El Bocadillo
email: brasserieelbocadillo@gmail.com
phone: '06 60 28 84 41'
description: > # this means to ignore newlines until "baseurl:"
baseurl: '/'
url: 'https://brasserieelbocadillo.fr'

instagram_username: el_bocadillo_beziers

# Build settings
markdown: kramdown

# Popup
popup_end_date: '2024-07-06'
popup_message: 'Rejoignez-nous le 5 juillet pour une soirée avec David Tobenaa à la Brasserie El Bocadillo. Réservez votre table !'
